language: r
sudo: false
cache: packages

matrix:
  include:
   - r: release
   - r: devel
   - r: oldrel

after_success:
  - Rscript -e 'covr::codecov()'

env:
  global:
   - _R_CHECK_SYSTEM_CLOCK_=FALSE
